### ISSUE TITLE
Warning: is_file is not within the allowed path(s)

### ISSUE THREAD

**Issue by piotr-cz** [ndeet/plg_system_less#13]
On the live site, I'm getting following PHP warnings:

**Warning**: is_file() [function.is-file]:open_basedir restriction in effect. File(/../../../media/jui/less/bootstrap-extended.less) is not within the allowed path(s): (/xxxxx/:/tmp:/usr/local/lib/php/:/usr/sbin/:/usr/bin/:/usr/local/bin/:/usr/local/sbin/:/bin/:/sbin/) in **/xxxxx/plugins/system/lessc.php** on line **80**

for each .less file imported using `@import` tag.
I'd say this is issue of the host, usually warning appears when template.css is recompiled.

What helps is to disable PHP warnings or Plugin (IMHO both should be disabled on live site anyway).

Update:
this seems to be Less compiler issue (lessc.php), already described here: [open_basedir restriction when parsing LESS files](http://stackoverflow.com/questions/13060067/open-basedir-restriction-when-parsing-less-files)

And in lessphp Issues: [http/https @import](https://github.com/leafo/lessphp/issues/428#issuecomment-20468541).

**Comment by ndeet** [comment]
Closing as this seems to be a problem with another 3rd party extension and no more feedback given.
