### ISSUE TITLE
Problem with &:extend(.foo);

### ISSUE THREAD

**Issue by saraheagle** [ndeet/plg_system_less#25]
Hello :) the complier seems to be having issues with compiling &:extend(.foo);

For example on Bootstrap3 grid.less &:extend(.clearfix all); I get error
lessphp error: parse error: failed at `ses&:extend(.clearfix all);` /home/directory/public_html/website/templates/template/less/bs3/mixins/grid.less on line 11

I have commented them out for now, but its not ideal if it can be fixed.
Thanks

**Comment by ndeet** [comment]
Hi, I released a new version 0.8.0 today. It includes a new compiler from https://github.com/oyejorge/less.php and should work with newer Bootstrap 3.3.4+ versions. Please choose lessphp-1.7.0.3 as compiler and see if the error still persists.

**Comment by epidote** [comment]
Hi, I have tried to use the lessphp-1.7.0.3 but I get a redeclaration problem. 
Fatal error: Cannot redeclare class lessc /XXXXX/libraries/vendor/leafo/lessphp/lessc.inc.php on line 41
Have tried a couple of different installs. 
Thanks

**Comment by Klipper** [comment]
I think you are using a conflicting extension or template which is using the leafo less.php.

**Comment by ndeet** [comment]
Closing as there was no further feedback.
