### ISSUE TITLE
bootstrap 3.3.4

### ISSUE THREAD

**Issue by pak7** [ndeet/plg_system_less#26]
Hello
Just noticed, that with bootstrap 3.3.4 I get the following error:
lessphp error: parse error: failed at `.img-retina(@file-1x; @file-2x; @width-1x; @height-1x) {`less/mixins/image.less on line 20 

It does no change if I select "lessc-0.3.9" or "lessc-0.4.0".
You got any clou or workaround for this problem?

Thanks

**Comment by smehrbrodt** [comment]
Same problem here.

**Comment by ndeet** [comment]
Hi guys, seems that newer bootstrap versions are not compatible anymore. Altough the maintainer of the less compiler (https://github.com/leafo/lessphp) released a new version the project seems pretty unmaintained (but I went from Less to Sass too and am a bit slow with updates - sorry). So maybe we should switch to the more active https://github.com/oyejorge/less.php - but I dont't know if it breaks old bootstrap versions. So I will have a look on the weekend and try lessphp-0.5.0 and/or switch to the less.php compiler.

**Comment by ndeet** [comment]
Ok I included the less compiler from @oyejorge (mentioned above) now and did some successfull tests with bootstrap 3.3.4. You can download the release 0.8.0 from here: https://github.com/ndeet/plg_system_less/releases

Joomla Extension auto updater will be available in the next few hours.
