### ISSUE TITLE
@import (reference) doesn't seem to work

### ISSUE THREAD

**Issue by philmarty** [ndeet/plg_system_less#32]
Hello,

I've installed your plugin, which is a great tool when using warp framework combined with brackets on my computer, as the yootheme less compiler dosen't offer enough options.

But I'm faced with a problem with the command @import
When I tried to import with the option 'reference' (as explained here : http://lesscss.org/features/#import-options) should compile the .less file and import all variables values without compiling the referenced file.
When I choose the lessc compiler this compilation option doesn't work (no value imlported for 0.3.9 or error with 0.4.0). It's only ok when using lesscphp compiler, but it is much more slower than the two others.

Do you think it is possible to fix the lessc compiler options?
Kindest regards
Philippe

**Comment by ndeet** [comment]
Hi, this functionality was implemented with lesscss.js v1.5.0 but leafo/lessphp 0.3.9 is based on lesscss.js 1.3 and 0.4.0 is based on lesscss.js 1.4. Seems that leafo/lessphp 0.5.0 is not following this versioning and is still on lesscss.js 1.4.0 (at least what i see in the git diff). So unless somebody backports this it won't be available.

**Comment by philmarty** [comment]
Ok, thanks for your answer. I hope to see a backport one day :)
