### ISSUE TITLE
Suport / development?

### ISSUE THREAD

**Issue by jjnxpct** [ndeet/plg_system_less#38]
Hi! I am just wondering if this plugin is still supported or developed any further?

**Comment by ndeet** [comment]
Hi @jjnxpct! 
I'm sorry but no, I switched completely to Drupal and most projects switched to SASS anyway. When still doing frontend on Joomla with LESS I use PHPStorm watcher plugin or some build tool like gulp or webpack to compile it with recent LESS versions. 

In hindsight, having the compiler on built into the site makes not much sense if you have some kind of build process / git workflow.

But if you or anybody else with some experience wants to update it to the latest versions PHP LESS compiler versions (if there are any still maintaned) feel free to submit a PR and I will check with current Joomla versions. After merging the PR I'm convinced it is in good hands and can transfer ownership of this repo and JED entry. Just want to avoid transferring ownership and risk somebody is distributing malware with it.

**Comment by jjnxpct** [comment]
Hi Ndeet,

Thanks for getting back to me on this. I think it would be best to review my workprocess as well. It would be best to compile less locally. But I am working with dreamweaver, and It's not easy to get that set up. It does include automatic less processing, but then I need to manually upload the CSS files. I tried other compilers but that only made my workflow more complicated.

Anyway, I will try and see if DW can get the job done the way I would like. If not, maybe check out a different IDE. 

I don't think I will be able to create a PR. I could ask a friended developer to see if he maybe can do this and also maybe would like to maintain this Joomla plugin for a while. But since this setup (compiling on server) might not be the bets way to go, I'm not sure its worth the effort. We'll see.

Kind regards,
Jip

**Comment by jjnxpct** [comment]
Hi! I changed my workflow (started using Prepros) so I won't be needing the Less plugin anymore for new sites.  So I won't need (want) ownership of this repo.

Kind regards,
Jip

**Comment by ndeet** [comment]
Hi Jip! Thanks for coming back and let me know - glad you found a proper workflow. I will close the issue now.
